on:
  push:
    branches:
      - main

jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: setup-node@v1
        with:
          node-version: latest
      - run: npm ci
      - run: npm run deploy